#!/usr/bin/env bash
# SSH client configuration to use private key ~/.ssh/school and disable password authentication
cat <<EOF > ~/.ssh/config
Host *
    IdentityFile ~/.ssh/school
    PasswordAuthentication no
EOF

