#!/usr/bin/env bash
# Configures Nginx to include X-Served-By header with the server hostname

# Install Nginx if not already installed
sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /var/www/html/index.html

# Performing a redirection
new_string="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com/b-kwizera permanent;"
sudo sed -i "s/server_name _;/$new_string/" /etc/nginx/sites-enabled/default

#Creating a custom error page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

# Custom HTTP response header
sudo sed -i "server_name _;/a add_header X-Server-By $HOSTNAME" /etc/nginx/sites-enabled/default

# Test for syntax errors
sudo nginx -t

# Restart Nginx to apply changes
sudo systemctl restart nginx

