#!/usr/bin/env bash
# Configures Nginx to include X-Served-By header with the server hostname

# Install Nginx if not already installed
sudo apt-get update -y
sudo apt-get install -y nginx

# Add custom header with hostname in the default Nginx site
sudo sed -i '/server_name _;/a \\tadd_header X-Served-By $HOSTNAME;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx

