#!/usr/bin/env bash
# Script that transfers a file from client to server using scp

# Check if less than 4 parameters are passed
if [ "$#" -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

# Assign parameters to variables
PATH_TO_FILE="$1"
IP="$2"
USERNAME="$3"
PATH_TO_SSH_KEY="$4"

# Transfer file using scp with strict host key checking disabled
scp -o StrictHostKeyChecking=no -i "~/.ssh/school" "some_page.html" "ubuntu@184.72.177.49:~/"

# Checking if transfer was successful
if [ $? -eq 0 ]; then
	echo "FILE WAS TRANSFERED SUCCESSFULLY"
else 
	echo "FILE TRANSFER FAILED"
fi
