#!/usr/bin/env bash
# Installs and configures Nginx to serve 'Holberton School' on port 80
apt-get update -y
apt-get install nginx -y
echo "Holberton School" | sudo tee /var/www/html/index.html
service nginx -t
sudo service nginx reload

