#!/usr/bin/env bash
# Installs and configures Nginx to serve 'Holberton School'

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw 'Nginx HTTP'
echo "Holberton School" | sudo tee /var/www/html/index.html

sudo nginx -t
sudo service nginx reload
