#!/usr/bin/env bash
# Configures Nginx to redirect /redirect_me to another page with 301 Moved Permanently

# Install Nginx if it is not already installed
sudo apt-get update
sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /etc/nginx/html/index.html

# Create a custom redirect in the default site configuration
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/github.com\/b-kwizera permanent;"
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Restart Nginx to apply changes
sudo service nginx restart

